name: Scrape laws

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  # 4시간마다

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install dependencies
        run: pip install -r scraper/requirements.txt

      - name: Run scraper
        run: python scraper/scrape.py > docs/index.json

      - name: Debug artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug
          path: docs/_debug

      - name: Commit & push
        run: |
          git config user.name "bot"
          git config user.email "actions@github.com"
          git add docs/index.json docs/_debug || true
          git pull --rebase origin main  # 여기가 추가: 푸시 전에 pull 해서 동기화
          git commit -m "update feed + debug" || true  # 변경 없으면 스킵
          git push origin main
